apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-container
          image: shm3215/eureka-server:latest
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  type: LoadBalancer
  selector:
    app: eureka-server
  ports:
    - nodePort: 31000
      port: 8761
      targetPort: 8761